//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスによって ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションを付けて
    // /str を使用するか、または Visual Studio プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されるキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、現在のスレッドの CurrentUICulture
        ///   プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}は必須です。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS001 {
            get {
                return ResourceManager.GetString("MS001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以上で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS002 {
            get {
                return ResourceManager.GetString("MS002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以下で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS003 {
            get {
                return ResourceManager.GetString("MS003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}byte以上で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS004 {
            get {
                return ResourceManager.GetString("MS004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}byte以下で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS005 {
            get {
                return ResourceManager.GetString("MS005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は半角英語で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS006 {
            get {
                return ResourceManager.GetString("MS006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は半角英数で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS007 {
            get {
                return ResourceManager.GetString("MS007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}はyyyy/MM/dd形式の正しい日付で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS008 {
            get {
                return ResourceManager.GetString("MS008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は数値形式で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS009 {
            get {
                return ResourceManager.GetString("MS009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}以下で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS010 {
            get {
                return ResourceManager.GetString("MS010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}以上で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS011 {
            get {
                return ResourceManager.GetString("MS011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力に誤りがあります。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string MS012 {
            get {
                return ResourceManager.GetString("MS012", resourceCulture);
            }
        }
    }
}
