// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     EntityGenerator 1.0.0
//   
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Prototype.Entities
{
    /// <summary>
    /// CLOB_01
    /// </summary>
    public class Clob01
    {
        /// <summary>
        /// ID
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// データ
        /// </summary>
        public string Data { get; set; }

        /// <summary>
        /// 備考
        /// </summary>
        public string Remark { get; set; }

    }
}
